article/urls.py
from . import views
from django.urls import path

app_name = 'article'

urlpatterns = [
    # article's urls
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset', include('password_reset.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
</head>
<body>
    {% include 'header.html' %}

    {% block content %}{% endblock content %}

    {% include 'footer.html' %}
    <script src="{% static 'jquery/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
</body>
</html>

templates/footer.html
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.argentdawn.top 2019 <a href="http://www.beian.miit.gov.cn">鲁ICP备19046938号</a></p>
    </div>
</footer>

templates/header.html
<!--定义导航栏-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
<!--        导航栏商标-->
        <a href="#" class="navbar-brand">我的博客</a>

        <div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'article:article_create' %}" class="nav-link">写文章</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'article:article_list' %}" class="nav-link">文章</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a href="#" class="dropdown-item" onclick="user_delete()">删除用户</a>
                        <a href="{% url 'userprofile:edit' user.id %}" class="dropdown-item">个人信息</a>
                        <a href="{% url 'userprofile:logout' %}" class="dropdown-item">退出登录</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'userprofile:login' %}" class="nav-link">登录</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% if user.is_authenticated %}
<form action="{% url 'userprofile:delete' user.id %}" style="display:none;" id="user_delete" method="post">
    {% csrf_token %}
    <button type="submit">发送</button>
</form>

<script>
function user_delete() {
    layer.open({
        title: '确认删除',
        content: '确认删除用户资料吗？',
        yes: function(index, layero) {
            $('form#user_delete button').click();
            layer.close(index);
        },
    })
}
</script>
{% endif %}