article/urls.py
from . import views
from django.urls import path

app_name = 'article'

urlpatterns = [
    # article's urls
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset', include('password_reset.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    total_views = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

article/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q

from .models import ArticlePost
from .form import ArticlePostForm
import markdown

# Create your views here.
def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')

    if search:
        if order == 'total_views':
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            ).order_by('-total_views')
        else:
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            )
    else:
        search = ''
        if order == 'total_views':
            article_list = ArticlePost.objects.all().order_by('-total_views')
        else:
            article_list = ArticlePost.objects.all()

    # if request.GET.get('order') == 'total_views':
    #     article_list = ArticlePost.objects.all().order_by('-total_views')
    #     order = 'total_views'
    # else:
    #     article_list = ArticlePost.objects.all()
    #     order = 'normal'


    paginator = Paginator(article_list, 3)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    context = { 'articles': articles, 'order': order, 'search': search }

    return render(request, 'article/list.html', context)

def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    article.total_views +=1
    article.save(update_fields=['total_views'])

    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ]
    )
    article.body = md.convert(article.body)
    context = {
        'article': article,
        'toc': md.toc
    }
    return render(request, 'article/detail.html', context)

@login_required(login_url='/userprofile/login/')
def article_create(request):
    if request.method == 'POST':
        article_post_form = ArticlePostForm(data=request.POST)

        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)

            new_article.author = User.objects.get(id=request.user.id)
            new_article.save()
            return redirect('article:article_list')
        else:
            return HttpResponse('表单有误，请重新填写。')
    else:
        article_post_form = ArticlePostForm()
        context = {
            'article_post_form': article_post_form
        }
        return render(request, 'article/create.html', context)

@login_required(login_url='/userprofile/login/')
def article_delete(request, id):
    article = ArticlePost.objects.get(id=id)
    article.delete()
    return redirect('article:article_list')

@login_required(login_url='/userprofile/login/')
def article_safe_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect('article:article_list')
    else:
        return HttpResponse('仅允许post请求')

@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    article = ArticlePost.objects.get(id=id)
    if request.user != article.author:
        return HttpResponse('抱歉，你无法修改这篇文章。')
    if request.method == 'POST':
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            return redirect('article:article_detail', id=id)
        else:
            return HttpResponse('表单内容有误，请重新填写。')
    else:
        article_post_form = ArticlePostForm()
        context = {
            'article': article,
            'article_post_form': article_post_form
        }
        return render(request, 'article/update.html', context)

templates/article/create.html
{% extends 'base.html' %} {% load static %}
{% block title %}写文章{% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form action="." method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <textarea name="body" id="body" cols="30" rows="12" class="form-control"></textarea>
                </div>
                <button class="btn btn-primary" type="submit">完成</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/article/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
文章详情
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <h1 class="col-12 mt-4 mb-4">
            {{ article.title }}
        </h1>
        <div class="col-9 alert alert-success">作者：{{ article.author }}
<!--            · <a href="#" onclick="confirm_delete()">删除文章</a>-->
            {% if user == article.author %}
            · <a href="#" onclick="confirm_safe_delete()">删除文章</a>
            · <a href="{% url 'article:article_update' article.id %}">编辑文章</a>
            {% endif %}
            <div>
                浏览：{{ article.total_views }}
            </div>

            <form action="{% url 'article:article_safe_delete' article.id %}" style="display:none;" id="safe_delete" method="POST">
                {% csrf_token %}
                <button type="submit">发送</button>
            </form>
        </div>
        <div class="col-3 mt-4">
            <h4><strong>目录</strong></h4>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
        </div>
        <div class="col-12">
            <p>{{ article.body|safe }}</p>
        </div>
    </div>
</div>

<script>
    function confirm_delete() {
        layer.open({
            title: '确认删除',
            content: '确认删除这篇文章？',
            yes: function(index, layero) {
                location.href='{% url "article:article_delete" article.id %}'
            },
        })
    }
    function confirm_safe_delete() {
        layer.open({
            title: '确认删除',
            content: '确认删除这篇文章吗？',
            yes: function(index, layero) {
                $('form#safe_delete button').click();
                layer.close(index);
            }
        })
    }
</script>

{% endblock content %}

templates/article/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
首页
{% endblock title %}

{% block content %}

<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?search={{ search }}">最新</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?order=total_views&search={{ search }}">最热</a>
            </li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline">
                <label class="sr-only">content</label>
                <input type="text" class="form-control mb-2 mr-sm-2" name="search" placeholder="搜索文章..." required>
            </form>
        </div>
    </div>

    {% if search %}
    {% if articles %}
    <h4><span style="color: red">{{ search }}</span>的搜索结果如下：</h4>
    {% else %}
    <h4>暂无<span style="color: red">{{ search }}</span>有关的文章。</h4>
    {% endif %}
    {% endif %}

    <div class="row mt-2">
        {% for article in articles %}
        <div class="col-4 mb-4">
            <div class="card h-100">
                <h4 class="card-header">{{ article.title }}</h4>
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                    <span>
                        <small class="col align-self-end" style="color: gray;">浏览：{{ article.total_views }}</small>
                    </span>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="paginator row">
        <div class="m-auto">
            <span class="step-links">
                {% if articles.has_previous %}
                <a href="?page=1&order={{ order }}&search={{ search }}" class="btn btn-success"> &laquo; 1</a>
                <span>...</span>
                <a href="?page{{ articles.previous_page_number }}&order={{ order }}&search={{ search }}" class="btn btn-secondary">{{ articles.previous_page_number }}</a>
                {% endif %}
                <span class="current btn btn-danger btn-lg">{{ articles.number }}</span>
                {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}" class="btn btn-secondary">{{ articles.next_page_number }}</a>
                <span>...</span>
                <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}" class="btn btn-success">{{ articles.paginator.num_pages }} &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>

{% endblock content %}

templates/article/update.html
{% extends 'base.html' %} {% load static %}
{% block title %}更新文章{% endblock title %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form action="." method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <textarea name="body" id="body" cols="30" rows="12">{{ article.body }}</textarea>
                </div>
                <button class="btn btn-primary" type="submit">完成</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}